project:
  type: website
  output-dir: docs
author: Alán F. Muñoz
date: last-modified

website:
  title: "JUMP documentation and examples"
  repo-url: https://github.com/broadinstitute/2023_12_JUMP_data_only_vignettes
  repo-actions: [edit, issue]
  reader-mode: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: Home
        contents:
         - index.md
      - section: How-to Guides
         - howto
      - section: Explanations
         - explanations

format:
  html:
    default-image-extension: svg
    theme:
      light: flatly
      dark: darkly
    code-fold: true
  ipynb:
    default-image-extension: svg
