project:
  type: website
  output-dir: docs
author: Alán F. Muñoz
date: last-modified

website:
  title: "JUMP documentation and examples"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: Home
        contents:
         - readme.md
      - section: How-to Guides
         - howto
      - section: Explanations
         - explanations
    tools:
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/broadinstitute/2023_12_JUMP_data_only_vignettes
          - text: Report a Bug
            url: https://github.com/broadinstitute/2023_12_JUMP_data_only_vignettes/issues/new

format:
  html:
    default-image-extension: svg
    theme:
      light: flatly
      dark: darkly
    code-fold: true
  ipynb:
    default-image-extension: svg
