project:
  type: website
  output-dir: docs
author: Alán F. Muñoz
date: last-modified

website:
  title: "JUMP stories and tutorials"
  sidebar:
    style: "docked"
    search: true
    contents: auto
    tools:
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/broadinstitute/2023_12_JUMP_data_only_vignettes
          - text: Report a Bug
            url: https://github.com/broadinstitute/2023_12_JUMP_data_only_vignettes/issues/new

format:
  html:
    theme:
      light: flatly
      dark: darkly
  ipynb: default
