name: Build website

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
      with:
        logger: pretty
        log-directives: nix_installer=trace
        backtrace: full

    - name: Nix cache
      uses: DeterminateSystems/magic-nix-cache-action@main

    #   run: |
    #     nix-build
    - name: Build development environment and run jupytext
      uses: rrbutani/use-nix-shell-action@v1
      with:
        file: shell.nix
        script: |
          jupytext --sync pills/scripts/*.py --execute
          quarto publish gh-pages --no-prompt --no-render

