name: Build website

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
      with:
        logger: pretty
        log-directives: nix_installer=trace
        backtrace: full

    - name: Nix cache
      uses: DeterminateSystems/magic-nix-cache-action@main

    # - name: Build development environment
    #   run: |
    #     nix-build
    - uses: rrbutani/use-nix-shell-action@v1
      with:
        file: shell.nix
        script: |
          jupytext --sync pills/scripts/*.py
          quarto publish gh-pages

    - uses: workflow/nix-shell-action@v3
      with:
        script: |
          jupytext --sync pills/scripts/*.py
          quarto publish gh-pages --no-prompt


    - name: Publish to GitHub Pages (and render)
      uses: b-rodrigues/quarto-nix-actions/publish@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
